sudo: true
language: cpp
compiler: gcc

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  # Debug
  - qmake travis_qmake_gcc_cpp14_boost_test.pro
  - make debug
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test
  # Release
  - qmake travis_qmake_gcc_cpp14_boost_test.pro
  - make release
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test
  # Test
  - qmake travis_qmake_gcc_cpp14_boost_test_test.pro
  - make debug
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test_test