language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev

script: 
  # Debug
  - qmake travis_qmake_gcc_cpp14_boost_test.pro
  - make debug
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test
  # Release
  - qmake travis_qmake_gcc_cpp14_boost_test.pro
  - make release
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test
  # Test
  - qmake travis_qmake_gcc_cpp14_boost_test_test.pro
  - make debug
  - make clean
  - ./travis_qmake_gcc_cpp14_boost_test_test
